[package]
name = "ekero"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
keywords = ["http", "tcp"]

[dependencies]
httparse = "1.10.0"
log = "0.4.25"

[dev-dependencies]
clang_log = "2.0.5"
